_target_: diffcsp.pl_modules.diffusion.CSPDiffusion
time_dim: 256
latent_dim: 0
cost_coord: 1.
cost_lattice: 1.
cost_slab_num_atoms: 1.  # Added: weight for slab_num_atoms prediction loss
max_neighbors: 30  # maximum number of neighbors for OTF graph bulding in decoder
radius: 8.  # maximum search radius for OTF graph building in decoder
timesteps: 1000
coord_type: frac
center_cart_coords: True

defaults:
  - decoder: cspnet
  - beta_scheduler: cosine
  - sigma_scheduler: wrapped
